const products = [
  {
    id: 1,
    name: "Airpods Wireless Bluetooth Headphones",
    description: "Description for product 1",
    price: 10.0,
    image: "/images/airpods.jpg",
    brand: "Apple",
    category: "Electronics",
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    id: 2,
    name: "Sony Playstation 4 Pro White Version",
    description: "Description for product 2",
    price: 20.0,
    image: "/images/playstation.jpg",
    brand: "Sony",
    category: "Electronics",
    countInStock: 5,
    rating: 4.0,
    numReviews: 8,
  },
  {
    id: 3,
    name: "iphone 11 Pro 256GB Memory",
    description: "Description for product 3",
    price: 30.0,
    image: "/images/phone.jpg",
    brand: "Apple",
    category: "Electronics",
    countInStock: 0,
    rating: 4.5,
    numReviews: 10,
  },
  {
    id: 4,
    name: "Logistech G-Series Gaming Mouse",
    description: "Description for product 4",
    price: 40.0,
    image: "/image/gamingmouse.jpg",
    brand: "Logitech",
    category: "Electronics",
    countInStock: 7,
    rating: 4.0,
    numReviews: 5,
  },
  {
    id: 5,
    name: "Amazon Echo Dot 3rd Gen",
    description: "Description for product 5",
    price: 50.0,
    image: "/images/alexa.jpg",
    brand: "Amazon",
    category: "Electronics",
    countInStock: 15,
    rating: 4.5,
    numReviews: 20,
  },
  // {
  //     id: 6,
  //     name: "Product 6",
  //     description: "Description for product 6",
  //     price: 60.0,
  //     image: "https://via.placeholder.com/150",
  // },
];
export default products;
